/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.domenkoder.aplikacijaigra;

/**
 *
 * @author domen
 */
public class Level1 extends javax.swing.JFrame {

    private final GameManager gameManager;

    public Level1() {
        initComponents();

        gameManager = new GameManager(
                this, (FadingLabel) spaceshipLabel,
                bgLabel,
                jLabelHeart1,
                jLabelHeart2,
                jLabelHeart3,
                4000 // spawn interval za Level 1
        );

        getContentPane().setComponentZOrder(bgLabel, getContentPane().getComponentCount() - 1);
        getContentPane().revalidate();
        getContentPane().repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelHeart1 = new javax.swing.JLabel();
        jLabelHeart2 = new javax.swing.JLabel();
        jLabelHeart3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        spaceshipLabel = new com.domenkoder.aplikacijaigra.FadingLabel();
        bgLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Space Ranger | Level 1");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelHeart1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/domenkoder/aplikacijaigra/images/heart.png"))); // NOI18N
        getContentPane().add(jLabelHeart1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jLabelHeart2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/domenkoder/aplikacijaigra/images/heart.png"))); // NOI18N
        getContentPane().add(jLabelHeart2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, -1, -1));

        jLabelHeart3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/domenkoder/aplikacijaigra/images/heart.png"))); // NOI18N
        getContentPane().add(jLabelHeart3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, -1, -1));

        jLabel1.setFont(new java.awt.Font("C&C Red Alert [INET]", 3, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Lives:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        spaceshipLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/domenkoder/aplikacijaigra/images/ezgif-31ef2d2cde44eff7.gif")));
        getContentPane().add(spaceshipLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 500, -1, -1));

        bgLabel.setForeground(new java.awt.Color(0, 0, 0));
        bgLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/domenkoder/aplikacijaigra/images/levelBg.jpg"))); // NOI18N
        getContentPane().add(bgLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        setSize(new java.awt.Dimension(1216, 809));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            //logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Level1().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bgLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelHeart1;
    private javax.swing.JLabel jLabelHeart2;
    private javax.swing.JLabel jLabelHeart3;
    private javax.swing.JLabel spaceshipLabel;
    // End of variables declaration//GEN-END:variables
}
