/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.domenkoder.aplikacijaigra;

/**
 *
 * @author domen
 */
public class Level2 extends javax.swing.JFrame {

    public Level2() {
        initComponents();

        new GameManager(
                this, (FadingLabel) spaceshipLabel,
                bgLabel,
                jLabelHeart1,
                jLabelHeart2,
                jLabelHeart3,
                jLabel3,
                jLabel4,
                1000
        );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        spaceshipLabel = new com.domenkoder.aplikacijaigra.FadingLabel();
        jLabelHeart1 = new javax.swing.JLabel();
        jLabelHeart2 = new javax.swing.JLabel();
        jLabelHeart3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        bgLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Space Ranger | Level 2");
        getContentPane().setLayout(null);

        spaceshipLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/domenkoder/aplikacijaigra/images/ezgif-31ef2d2cde44eff7.gif"))); // NOI18N
        spaceshipLabel.setLabelFor(spaceshipLabel);
        getContentPane().add(spaceshipLabel);
        spaceshipLabel.setBounds(480, 530, 300, 222);

        jLabelHeart1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/domenkoder/aplikacijaigra/images/heart.png"))); // NOI18N
        getContentPane().add(jLabelHeart1);
        jLabelHeart1.setBounds(30, 80, 75, 75);

        jLabelHeart2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/domenkoder/aplikacijaigra/images/heart.png"))); // NOI18N
        getContentPane().add(jLabelHeart2);
        jLabelHeart2.setBounds(110, 80, 75, 75);

        jLabelHeart3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/domenkoder/aplikacijaigra/images/heart.png"))); // NOI18N
        getContentPane().add(jLabelHeart3);
        jLabelHeart3.setBounds(190, 80, 75, 75);

        jLabel4.setFont(new java.awt.Font("C&C Red Alert [INET]", 3, 48)); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(1000, 110, 230, 50);

        jLabel3.setFont(new java.awt.Font("C&C Red Alert [INET]", 3, 48)); // NOI18N
        jLabel3.setText("0");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(1000, 40, 230, 50);

        jLabel1.setFont(new java.awt.Font("C&C Red Alert [INET]", 3, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Lives:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 30, 114, 48);

        bgLabel.setForeground(new java.awt.Color(0, 0, 0));
        bgLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/domenkoder/aplikacijaigra/images/levelBg.jpg"))); // NOI18N
        getContentPane().add(bgLabel);
        bgLabel.setBounds(0, 0, 2000, 800);

        setSize(new java.awt.Dimension(1216, 809));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            //logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Level2().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bgLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelHeart1;
    private javax.swing.JLabel jLabelHeart2;
    private javax.swing.JLabel jLabelHeart3;
    private javax.swing.JLabel spaceshipLabel;
    // End of variables declaration//GEN-END:variables
}
