/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.domenkoder.aplikacijaigra;

import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.Timer;

/**
 *
 * @author domen
 */
public class Level1 extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Level1.class.getName());

    ArrayList<Rock> rocks = new ArrayList<>();

    int lives = 3;
    boolean gameOver = false;

    Timer spawnTimer;
    Timer moveTimer;

    int playerX = 500;
    int playerY = 500;

    /**
     * Creates new form Level1
     */
    public Level1() {
        initComponents();
        getContentPane().setComponentZOrder(bgLabel, getContentPane().getComponentCount() - 1);
        getContentPane().revalidate();
        getContentPane().repaint();

        setFocusable(true);
        requestFocusInWindow();

        //Ship movement
        addKeyListener(new KeyAdapter() {
            @Override
            public void keyPressed(KeyEvent e) {
                if (e.getKeyCode() == KeyEvent.VK_LEFT) {
                    playerX -= 10;
                }
                if (e.getKeyCode() == KeyEvent.VK_RIGHT) {
                    playerX += 10;
                }
                // Bounds
                if (playerX < 0) {
                    playerX = 0;
                }

                if (playerX > 1200 - 300) {
                    playerX = 1200 - 300;
                }
                spaceshipLabel.setLocation(playerX, playerY); // premakni JLabel
            }

        });

        //Rocks spawning
        spawnTimer = new Timer(4000, e -> { // vsakih 5 sekund
            int screenWidth = getContentPane().getWidth();
            int randomX = (int) (Math.random() * (screenWidth - 80));

            Rock r = new Rock(randomX);
            rocks.add(r);

            getContentPane().add(r,
                    new org.netbeans.lib.awtextra.AbsoluteConstraints(randomX, -80, 80, 80));

            getContentPane().setComponentZOrder(r, 0);
        });
        spawnTimer.start();

        //Rocks movement
        moveTimer = new Timer(16, e -> {

            ArrayList<Rock> toRemove = new ArrayList<>();

            for (Rock r : rocks) {
                r.move();

                // bottom border
                if (r.getY() > getContentPane().getHeight()) {
                    getContentPane().remove(r);
                    toRemove.add(r);
                }

                if (playerX < 0) {
                    playerX = 0;
                }
                if (playerX > 1200 - 300) {
                    playerX = 1200 - 300;
                }
                spaceshipLabel.setLocation(playerX, playerY);

                // collision with spaceshipom
                if (!gameOver && r.getBounds().intersects(spaceshipLabel.getBounds())) {
                    lives--;
                    System.out.println("BOOM 💥  Lives left: " + lives);

                    // delete rock
                    getContentPane().remove(r);
                    toRemove.add(r);

                    // Flash effect
                    Timer flashTimer = new Timer(100, null);
                    final int[] count = {0};
                    flashTimer.addActionListener(ev -> {
                        float newAlpha = (count[0] % 2 == 0) ? 0f : 1f;
                        ((FadingLabel) spaceshipLabel).setAlpha(newAlpha);
                        count[0]++;
                        if (count[0] >= 6) {
                            ((FadingLabel) spaceshipLabel).setAlpha(1f);
                            flashTimer.stop();
                        }
                    });
                    flashTimer.start();

                    if (lives <= 0) {
                        gameOver = true;
                        spawnTimer.stop();
                        moveTimer.stop();
                        System.out.println("GAME OVER 💀");
                    }
                }
            }

            rocks.removeAll(toRemove);
            getContentPane().repaint();
        });
        moveTimer.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        spaceshipLabel = new com.domenkoder.aplikacijaigra.FadingLabel();
        bgLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Space Ranger | Level 1");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        spaceshipLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/domenkoder/aplikacijaigra/images/ezgif-31ef2d2cde44eff7.gif"))); // NOI18N
        getContentPane().add(spaceshipLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 500, -1, -1));

        bgLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/domenkoder/aplikacijaigra/images/levelBg.jpg"))); // NOI18N
        getContentPane().add(bgLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        setSize(new java.awt.Dimension(1216, 809));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Level1().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bgLabel;
    private javax.swing.JLabel spaceshipLabel;
    // End of variables declaration//GEN-END:variables
}
